export default {
  'primary-1': 'replace tint(@primary-color, 90%)',
  'primary-2': 'replace tint(@primary-color, 80%)',
  'primary-3': 'unused',
  'primary-4': 'unused',
  'primary-5':
    'color used to control the text color in many active and hover states, replace tint(@primary-color, 20%)',
  'primary-6':
    "color used to control the text color of active buttons, don't use, use @primary-color",
  'primary-7': 'replace shade(@primary-color, 5%)',
  'primary-8': 'unused',
  'primary-9': 'unused',
  'primary-10': 'unused',
  'padding-lg': 'containers',
  'padding-md': 'small containers and buttons',
  'padding-sm': 'Form controls and items',
  'padding-xs': 'small items',
  'padding-xss': 'more small',
  'margin-lg': 'containers',
  'margin-md': 'small containers and buttons',
  'margin-sm': 'Form controls and items',
  'margin-xs': 'small items',
  'margin-xss': 'more small',
  'border-color-base': 'base border outline a component',
  'border-color-split': 'split border inside a component',
  'border-width-base': 'width of the border for a component',
  'border-style-base': 'style of a components border',
  'background-color-light': 'background of header and selected item',
  'background-color-base': 'Default grey background color',
  'animation-duration-slow': 'Modal',
  'animation-duration-fast': 'Tooltip',
  'select-multiple-item-height': 'Normal 24px',
  'progress-text-color':
    'This is for circle text color, should be renamed better',
}
